// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserCommonLogin = "user_common_login"

// UserCommonLogin mapped from table <user_common_login>
type UserCommonLogin struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID        int64     `gorm:"column:uuid;not null" json:"uuid"`                 // 用户标示
	UserName    string    `gorm:"column:user_name;not null" json:"user_name"`       // 登录用户名
	PhoneNumber string    `gorm:"column:phone_number;not null" json:"phone_number"` // 登录手机号
	IP          string    `gorm:"column:ip;not null" json:"ip"`                     // 登录IP地址
	Location    string    `gorm:"column:location;not null" json:"location"`         // 登录地点
	Browser     string    `gorm:"column:browser;not null" json:"browser"`           // 浏览器类型
	Os          string    `gorm:"column:os;not null" json:"os"`                     // 操作系统
	Status      int32     `gorm:"column:status;not null" json:"status"`             // 登录状态（0成功 1失败）
	Msg         string    `gorm:"column:msg;not null" json:"msg"`                   // 提示消息
	LoginAt     time.Time `gorm:"column:login_at;not null" json:"login_at"`         // 登录时间
	Client      string    `gorm:"column:client;not null" json:"client"`             // 登录客户端：web，wx，dy，app
}

// TableName UserCommonLogin's table name
func (*UserCommonLogin) TableName() string {
	return TableNameUserCommonLogin
}
