// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserCommonOnline = "user_common_online"

// UserCommonOnline mapped from table <user_common_online>
type UserCommonOnline struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID           int64     `gorm:"column:uuid;not null" json:"uuid"`                         // 用户标识
	LoginAt        time.Time `gorm:"column:login_at;not null" json:"login_at"`                 // 登录时间
	UserName       string    `gorm:"column:user_name;not null" json:"user_name"`               // 用户名
	PhoneNumber    string    `gorm:"column:phone_number;not null" json:"phone_number"`         // 手机号
	Token          string    `gorm:"column:token;not null" json:"token"`                       // 用户token
	TokenExpiredAt time.Time `gorm:"column:token_expired_at;not null" json:"token_expired_at"` // token过期时间
	IP             string    `gorm:"column:ip;not null" json:"ip"`                             // 登录ip
	Explorer       string    `gorm:"column:explorer;not null" json:"explorer"`                 // 浏览器
	Os             string    `gorm:"column:os;not null" json:"os"`                             // 操作系统
	Client         string    `gorm:"column:client;not null" json:"client"`                     // 登录客户端：web，wx，dy，app
}

// TableName UserCommonOnline's table name
func (*UserCommonOnline) TableName() string {
	return TableNameUserCommonOnline
}
