// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserCommonPost = "user_common_post"

// UserCommonPost mapped from table <user_common_post>
type UserCommonPost struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 岗位ID
	PostCode  string    `gorm:"column:post_code;not null" json:"post_code"`        // 岗位编码
	PostName  string    `gorm:"column:post_name;not null" json:"post_name"`        // 岗位名称
	Level     int32     `gorm:"column:level;not null" json:"level"`                // 层级
	Status    int32     `gorm:"column:status;not null" json:"status"`              // 状态（0正常 1停用）
	Remark    string    `gorm:"column:remark;not null" json:"remark"`              // 备注
	RoleIds   string    `gorm:"column:role_ids;not null" json:"role_ids"`          // 关联角色数据
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`               // 修改时间
}

// TableName UserCommonPost's table name
func (*UserCommonPost) TableName() string {
	return TableNameUserCommonPost
}
