// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserCommonRole = "user_common_role"

// UserCommonRole mapped from table <user_common_role>
type UserCommonRole struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Status    int32     `gorm:"column:status;not null" json:"status"`                   // 0:禁用 1:正常
	Level     int32     `gorm:"column:level;not null" json:"level"`                     // 层级
	Name      string    `gorm:"column:name;not null" json:"name"`                       // 角色名称
	Remark    string    `gorm:"column:remark;not null" json:"remark"`                   // 备注
	DataScope int32     `gorm:"column:data_scope;not null;default:4" json:"data_scope"` // 数据范围1：全部 2：直系 3：本部门及以下 4：仅本部门
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`                    // 创建时间
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`                    // 更新时间
}

// TableName UserCommonRole's table name
func (*UserCommonRole) TableName() string {
	return TableNameUserCommonRole
}
