// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserCommonKv = "user_common_kv"

// UserCommonKv mapped from table <user_common_kv>
type UserCommonKv struct {
	Key   string `gorm:"column:key;primaryKey" json:"key"`   // key值
	Value string `gorm:"column:value;not null" json:"value"` // value值
}

// TableName UserCommonKv's table name
func (*UserCommonKv) TableName() string {
	return TableNameUserCommonKv
}
