// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserAdminInfo = "user_admin_info"

// UserAdminInfo mapped from table <user_admin_info>
type UserAdminInfo struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UUID          int64          `gorm:"column:uuid;not null" json:"uuid"`                         // 人员唯一标识符
	UserName      string         `gorm:"column:user_name;not null" json:"user_name"`               // 用户名
	PhoneNumber   string         `gorm:"column:phone_number;not null" json:"phone_number"`         // +国家代码 手机号
	RealName      string         `gorm:"column:real_name;not null" json:"real_name"`               // 真实姓名
	UserPassword  string         `gorm:"column:user_password;not null" json:"user_password"`       // 登录密码;cmf_password加密
	UserStatus    int32          `gorm:"column:user_status;not null;default:1" json:"user_status"` // 用户状态;0:禁用,1:正常,2:未验证
	UserEmail     string         `gorm:"column:user_email;not null" json:"user_email"`             // 用户邮箱
	UserMode      int32          `gorm:"column:user_mode;not null;default:1" json:"user_mode"`     // 1:内部用户 2:外部用户
	UserAddress   string         `gorm:"column:user_address;not null" json:"user_address"`         // 联系地址
	IdentityNum   string         `gorm:"column:identity_num;not null" json:"identity_num"`         // 身份证号
	Sex           int32          `gorm:"column:sex;not null" json:"sex"`                           // 性别;0:保密,1:男,2:女
	Avatar        string         `gorm:"column:avatar;not null" json:"avatar"`                     // 用户头像
	DeptID        int32          `gorm:"column:dept_id;not null" json:"dept_id"`                   // 部门id
	PostID        int32          `gorm:"column:post_id;not null" json:"post_id"`                   // 岗位id
	Remark        string         `gorm:"column:remark;not null" json:"remark"`                     // 备注
	Describe      string         `gorm:"column:describe;not null" json:"describe"`                 // 描述信息
	WxOpenID      string         `gorm:"column:wx_open_id;not null" json:"wx_open_id"`             // 微信openid
	DyOpenID      string         `gorm:"column:dy_open_id;not null" json:"dy_open_id"`             // 抖音openid
	LastLoginIP   string         `gorm:"column:last_login_ip;not null" json:"last_login_ip"`       // 最后登录ip
	LastLoginTime time.Time      `gorm:"column:last_login_time" json:"last_login_time"`            // 最后登录时间
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`                      // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`                      // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                      // 删除时间
}

// TableName UserAdminInfo's table name
func (*UserAdminInfo) TableName() string {
	return TableNameUserAdminInfo
}
