// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/wheelergeo/g-otter-micro-user/biz/dal/model"
)

func newUserCommonRole(db *gorm.DB, opts ...gen.DOOption) userCommonRole {
	_userCommonRole := userCommonRole{}

	_userCommonRole.userCommonRoleDo.UseDB(db, opts...)
	_userCommonRole.userCommonRoleDo.UseModel(&model.UserCommonRole{})

	tableName := _userCommonRole.userCommonRoleDo.TableName()
	_userCommonRole.ALL = field.NewAsterisk(tableName)
	_userCommonRole.ID = field.NewInt32(tableName, "id")
	_userCommonRole.Status = field.NewInt32(tableName, "status")
	_userCommonRole.Level = field.NewInt32(tableName, "level")
	_userCommonRole.Name = field.NewString(tableName, "name")
	_userCommonRole.Remark = field.NewString(tableName, "remark")
	_userCommonRole.DataScope = field.NewInt32(tableName, "data_scope")
	_userCommonRole.CreatedAt = field.NewTime(tableName, "created_at")
	_userCommonRole.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userCommonRole.fillFieldMap()

	return _userCommonRole
}

type userCommonRole struct {
	userCommonRoleDo userCommonRoleDo

	ALL       field.Asterisk
	ID        field.Int32
	Status    field.Int32  // 0:禁用 1:正常
	Level     field.Int32  // 层级
	Name      field.String // 角色名称
	Remark    field.String // 备注
	DataScope field.Int32  // 数据范围1：全部 2：直系 3：本部门及以下 4：仅本部门
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (u userCommonRole) Table(newTableName string) *userCommonRole {
	u.userCommonRoleDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userCommonRole) As(alias string) *userCommonRole {
	u.userCommonRoleDo.DO = *(u.userCommonRoleDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userCommonRole) updateTableName(table string) *userCommonRole {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.Status = field.NewInt32(table, "status")
	u.Level = field.NewInt32(table, "level")
	u.Name = field.NewString(table, "name")
	u.Remark = field.NewString(table, "remark")
	u.DataScope = field.NewInt32(table, "data_scope")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userCommonRole) WithContext(ctx context.Context) *userCommonRoleDo {
	return u.userCommonRoleDo.WithContext(ctx)
}

func (u userCommonRole) TableName() string { return u.userCommonRoleDo.TableName() }

func (u userCommonRole) Alias() string { return u.userCommonRoleDo.Alias() }

func (u *userCommonRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userCommonRole) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["status"] = u.Status
	u.fieldMap["level"] = u.Level
	u.fieldMap["name"] = u.Name
	u.fieldMap["remark"] = u.Remark
	u.fieldMap["data_scope"] = u.DataScope
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userCommonRole) clone(db *gorm.DB) userCommonRole {
	u.userCommonRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userCommonRole) replaceDB(db *gorm.DB) userCommonRole {
	u.userCommonRoleDo.ReplaceDB(db)
	return u
}

type userCommonRoleDo struct{ gen.DO }

func (u userCommonRoleDo) Debug() *userCommonRoleDo {
	return u.withDO(u.DO.Debug())
}

func (u userCommonRoleDo) WithContext(ctx context.Context) *userCommonRoleDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userCommonRoleDo) ReadDB() *userCommonRoleDo {
	return u.Clauses(dbresolver.Read)
}

func (u userCommonRoleDo) WriteDB() *userCommonRoleDo {
	return u.Clauses(dbresolver.Write)
}

func (u userCommonRoleDo) Session(config *gorm.Session) *userCommonRoleDo {
	return u.withDO(u.DO.Session(config))
}

func (u userCommonRoleDo) Clauses(conds ...clause.Expression) *userCommonRoleDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userCommonRoleDo) Returning(value interface{}, columns ...string) *userCommonRoleDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userCommonRoleDo) Not(conds ...gen.Condition) *userCommonRoleDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userCommonRoleDo) Or(conds ...gen.Condition) *userCommonRoleDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userCommonRoleDo) Select(conds ...field.Expr) *userCommonRoleDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userCommonRoleDo) Where(conds ...gen.Condition) *userCommonRoleDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userCommonRoleDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *userCommonRoleDo {
	return u.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (u userCommonRoleDo) Order(conds ...field.Expr) *userCommonRoleDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userCommonRoleDo) Distinct(cols ...field.Expr) *userCommonRoleDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userCommonRoleDo) Omit(cols ...field.Expr) *userCommonRoleDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userCommonRoleDo) Join(table schema.Tabler, on ...field.Expr) *userCommonRoleDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userCommonRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *userCommonRoleDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userCommonRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) *userCommonRoleDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userCommonRoleDo) Group(cols ...field.Expr) *userCommonRoleDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userCommonRoleDo) Having(conds ...gen.Condition) *userCommonRoleDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userCommonRoleDo) Limit(limit int) *userCommonRoleDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userCommonRoleDo) Offset(offset int) *userCommonRoleDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userCommonRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *userCommonRoleDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userCommonRoleDo) Unscoped() *userCommonRoleDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userCommonRoleDo) Create(values ...*model.UserCommonRole) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userCommonRoleDo) CreateInBatches(values []*model.UserCommonRole, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userCommonRoleDo) Save(values ...*model.UserCommonRole) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userCommonRoleDo) First() (*model.UserCommonRole, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonRole), nil
	}
}

func (u userCommonRoleDo) Take() (*model.UserCommonRole, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonRole), nil
	}
}

func (u userCommonRoleDo) Last() (*model.UserCommonRole, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonRole), nil
	}
}

func (u userCommonRoleDo) Find() ([]*model.UserCommonRole, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserCommonRole), err
}

func (u userCommonRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserCommonRole, err error) {
	buf := make([]*model.UserCommonRole, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userCommonRoleDo) FindInBatches(result *[]*model.UserCommonRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userCommonRoleDo) Attrs(attrs ...field.AssignExpr) *userCommonRoleDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userCommonRoleDo) Assign(attrs ...field.AssignExpr) *userCommonRoleDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userCommonRoleDo) Joins(fields ...field.RelationField) *userCommonRoleDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userCommonRoleDo) Preload(fields ...field.RelationField) *userCommonRoleDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userCommonRoleDo) FirstOrInit() (*model.UserCommonRole, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonRole), nil
	}
}

func (u userCommonRoleDo) FirstOrCreate() (*model.UserCommonRole, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserCommonRole), nil
	}
}

func (u userCommonRoleDo) FindByPage(offset int, limit int) (result []*model.UserCommonRole, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userCommonRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userCommonRoleDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userCommonRoleDo) Delete(models ...*model.UserCommonRole) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userCommonRoleDo) withDO(do gen.Dao) *userCommonRoleDo {
	u.DO = *do.(*gen.DO)
	return u
}
